DROP TABLE IF EXISTS TASKS;

DROP TABLE IF EXISTS PROJECT_DETAILS;
DROP TABLE IF EXISTS PROJECT_TAGS;
DROP TABLE IF EXISTS PROJECTS;

DROP TABLE IF EXISTS TAGS;

CREATE TABLE PROJECTS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL,
  DESCRIPTION VARCHAR(250) NOT NULL
);

CREATE TABLE PROJECT_DETAILS(
  	ID INT AUTO_INCREMENT PRIMARY KEY,
	CREATED_BY VARCHAR(250) NOT NULL,
	PROJECT_ID INT,
	foreign key (PROJECT_ID) references PROJECTS(ID)
);

CREATE TABLE TAGS(
  	ID INT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(250) NOT NULL
);

CREATE TABLE PROJECT_TAGS(
  	ID INT AUTO_INCREMENT PRIMARY KEY,
  	PROJECT_ID INT,
  	TAG_ID INT,
	foreign key (PROJECT_ID) references PROJECTS(ID),
	foreign key (TAG_ID) references TAGS(ID)
);

CREATE TABLE TASKS (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  DESCRIPTION VARCHAR(250) NOT NULL,
  PROJECT_ID INT,
  foreign key (PROJECT_ID) references PROJECTS(ID)
);
