name: master-build

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: warchant/setup-sonar-scanner@v3
        with:
          java-version: 1.8
      - name: Build with Maven
        run: sonar-scanner -Dsonar.login=${{secrets.SONAR_TOKEN}} -Dsonar.organization=${{secrets.SONAR_ORGANIZATION}} -Dsonar.host.url=${{secrets.SONAR_HOST}} -Dsonar.scanner.force-deprecated-java-version=true 
